import LegalDocument, { LegalList, LegalSection } from "@/components/legal/LegalDocument";

export const metadata = { title: "Privacy Policy", description: "How Mindsettle collects, uses, stores and protects personal information." };

export default function PrivacyPage() {
  return <LegalDocument eyebrow="Your information matters" title="Privacy Policy" intro="Mindsettle is committed to providing quality services and managing personal information responsibly.">
    <LegalSection title="Our Privacy Obligations"><p>Mindsettle has adopted the Australian Privacy Principles contained in the Privacy Act 1988 (Cth). These principles govern the way we collect, use, disclose, store, secure and dispose of Personal Information.</p><p>More information about the Australian Privacy Principles is available from the <a href="https://www.oaic.gov.au/privacy/australian-privacy-principles" target="_blank" rel="noreferrer" className="font-semibold text-[#285c4f] underline underline-offset-4">Office of the Australian Information Commissioner</a>.</p></LegalSection>
    <LegalSection title="What is Personal Information and why do we collect it?"><p>Personal Information is information or an opinion that identifies an individual. Examples of Personal Information we collect include names, addresses, email addresses and telephone numbers.</p><p>We may obtain Personal Information through interviews and correspondence, by telephone, email, our website at www.mindsettle.com, publicly available sources, cookies and third parties. We do not guarantee the website links or privacy policies of authorised third parties.</p><p>We collect Personal Information primarily to provide our services, supply information to clients and conduct marketing. We may also use it for related secondary purposes where you would reasonably expect that use or disclosure. You may unsubscribe from mailing or marketing lists at any time by contacting us in writing.</p><p>When we collect Personal Information, we will, where appropriate and possible, explain why it is being collected and how we plan to use it.</p></LegalSection>
    <LegalSection title="Sensitive Information"><p>Sensitive information is defined in the Privacy Act and includes information or opinions about matters such as racial or ethnic origin, political opinions, association memberships, religious or philosophical beliefs, trade union or professional memberships, criminal records and health information.</p><p>Sensitive information will be used only:</p><LegalList><li>For the primary purpose for which it was obtained.</li><li>For a secondary purpose directly related to the primary purpose.</li><li>With your consent.</li><li>Where required or authorised by law.</li></LegalList></LegalSection>
    <LegalSection title="Third Parties"><p>Where reasonable and practicable, we collect Personal Information only from you. In some circumstances, third parties may provide information to us. In that case, we will take reasonable steps to ensure you are made aware of the information provided.</p></LegalSection>
    <LegalSection title="Disclosure of Personal Information"><p>Your Personal Information may be disclosed to third parties where you consent to the use or disclosure, or where disclosure is required or authorised by law.</p></LegalSection>
    <LegalSection title="Security of Personal Information"><p>Personal Information is stored in a manner that reasonably protects it from misuse, loss, unauthorised access, modification or disclosure.</p><p>When Personal Information is no longer needed for the purpose for which it was obtained, we will take reasonable steps to destroy it or permanently de-identify it. Most Personal Information stored in client files will be kept for a minimum of seven years.</p></LegalSection>
    <LegalSection title="Access to your Personal Information"><p>You may access the Personal Information we hold about you and request that it be updated or corrected, subject to certain exceptions. To request access, contact us in writing.</p><p>Mindsettle does not charge for an access request but may charge an administrative fee for supplying a copy of your Personal Information. To protect your information, we may require identification before releasing it.</p></LegalSection>
    <LegalSection title="Maintaining the Quality of your Personal Information"><p>It is important that your Personal Information is accurate, complete and current. If you believe information we hold is out of date or inaccurate, please advise us as soon as practicable so we can update our records.</p></LegalSection>
    <LegalSection title="Policy Updates"><p>This Policy may change from time to time. The current version will remain available on our website.</p></LegalSection>
    <LegalSection title="Privacy Complaints and Enquiries"><p>Questions or complaints about this Privacy Policy can be directed to:</p><address className="not-italic"><p>Mindsettle<br />P.O. Box 2<br />Lutwyche QLD 4030</p><p><a href="mailto:mindsettle@gmail.com" className="font-semibold text-[#285c4f] underline underline-offset-4">mindsettle@gmail.com</a><br /><a href="tel:+61434486690" className="font-semibold text-[#285c4f] underline underline-offset-4">+61 434 486 690</a></p></address></LegalSection>
  </LegalDocument>;
}
