export const metadata = { title: "Contact", description: "Contact Mindsettle about bringing calming visual and musical experiences into your clinical setting." };

const SOCIALS = [["Instagram", "https://www.instagram.com/mindsettle/"], ["LinkedIn", "https://www.linkedin.com/company/mindsettle/?viewAsMember=true"], ["Facebook", "https://www.facebook.com/mindsettling"]];

export default function ContactPage() {
  return <>
    <section className="bg-[#dce8ca] px-6 pb-20 pt-44 sm:pb-28"><div className="mx-auto max-w-7xl lg:px-4"><p className="eyebrow">Get in touch</p><h1 className="mt-5 max-w-4xl text-balance text-5xl font-semibold leading-[1.05] tracking-[-0.045em] text-[#163d34] sm:text-7xl">We&apos;d love to hear from you.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#4b615b]">Whether you&apos;re a potential client or collaborator, please get in touch.</p></div></section>
    <section className="bg-[#f8f8f2] py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-[.8fr_1.2fr] lg:gap-24 lg:px-10"><div><p className="eyebrow">Contact Mindsettle</p><div className="mt-8 space-y-3"><a href="tel:+61434486690" className="block text-2xl font-semibold text-[#163d34] transition hover:text-[#4f745e]">+61 434 486 690</a><a href="mailto:mindsettle@gmail.com" className="block text-2xl font-semibold text-[#163d34] transition hover:text-[#4f745e]">mindsettle@gmail.com</a></div><div className="mt-10 flex flex-wrap gap-3">{SOCIALS.map(([label, href]) => <a key={label} href={href} target="_blank" rel="noreferrer" className="rounded-full border border-[#163d34]/20 px-4 py-2 text-sm font-semibold text-[#163d34] transition hover:bg-[#dce8ca]">{label} ↗</a>)}</div></div><form action="mailto:mindsettle@gmail.com" method="post" encType="text/plain" className="rounded-[2rem] bg-white p-7 shadow-[0_20px_60px_rgba(22,61,52,.08)] sm:p-10"><h2 className="text-2xl font-semibold text-[#163d34]">Tell us a little about your enquiry</h2><div className="mt-8 grid gap-6 sm:grid-cols-2">{[["Name *", "name", "text"], ["Email *", "email", "email"], ["Subject", "subject", "text"]].map(([label, name, type], index) => <label key={name} className={`text-sm font-semibold text-[#435b54] ${index === 2 ? "sm:col-span-2" : ""}`}>{label}<input name={name} type={type} required={index < 2} className="mt-2 w-full rounded-xl border border-[#cad5ce] bg-[#fafbf7] px-4 py-3.5 font-normal outline-none focus:border-[#4f745e] focus:ring-2 focus:ring-[#dce8ca]" /></label>)}<label className="text-sm font-semibold text-[#435b54] sm:col-span-2">Message *<textarea name="message" required rows={6} className="mt-2 w-full resize-none rounded-xl border border-[#cad5ce] bg-[#fafbf7] px-4 py-3.5 font-normal outline-none focus:border-[#4f745e] focus:ring-2 focus:ring-[#dce8ca]" /></label></div><button type="submit" className="mt-7 rounded-full bg-[#163d34] px-7 py-3.5 text-sm font-semibold text-white transition hover:bg-[#285c4f]">Send enquiry ↗</button></form></div></section>
  </>;
}
